### PR TITLE
Use numpy's memmap and avoid changing ostream's file mode

### PR DESCRIPTION
**Pull request by saimn**
@Cadair @astrofrog : proposal to avoid changing ostream mode by creating the memmap from the file name instead of reusing the file descriptor. Also I use numpy, but could do the same directly with mmap.

### CODE REVIEW

**Comment by astrofrog** [comment]
I can try this out today on Windows to see how it behaves there. If there is no public API for closing the mmap with Numpy I think using mmap as we do right now would be better.

**Comment by Cadair** [comment]
It feels a little gross to open a second file handle to the same file. I do think we should avoid doing this if the mode of the file allows us to write.

**Comment by saimn** [comment]
I missed the merge notification, was listening to a meeting while adding more tests, so I pushed another commit here :grin:

**Comment by Cadair** [comment]
pushed were? ended up on the main PR?

**Comment by saimn** [comment]
So I can see arguments for doing it the hard way, but I still think the np.memmap version was much simpler ;)

**Comment by saimn** [comment]
No, pushed after the merge, so I opened another PR here.

**Pull request merged**
